#!/usr/bin/ruby
require_relative 'dirTools.rb'

def usage()
    return "usage:\n    setd <name> [path]"
end

if ARGV.length == 1
    defs = DirTools.loadDefs
    ret = defs.delete(ARGV[0])
    if (ret)
        puts ret
        DirTools.saveDefs(defs)
        exit 0
    else
        $stderr.puts "ERROR:#{ARGV[0]} not found"
        exit -1
    end
end

$stderr.puts usage
exit -1
