#!/usr/bin/ruby
require_relative 'dirTools.rb'

def usage()
    return "usage:\n    listd [<name>]"
end

if ARGV.length != 0
    puts usage
    exit -1
end

defs = DirTools.loadDefs

defs.keys.each {|x|
    puts "#{x}\t#{defs[x]}"
}
exit 0

