#!/usr/bin/ruby
require_relative 'dirTools.rb'

def usage()
    return "usage:\n    listd"
end

if ARGV.length != 0
    puts usage
    exit -1
end

defs = DirTools.loadDefs().sort_by {|name, dir| name}

defs.each {|x|
    puts "#{x[0]}\t#{x[1]}"
}
exit 0

