#!/usr/bin/ruby
require_relative 'dirTools.rb'

def usage()
    return "usage:\n    listd"
end

if ARGV.length != 0
    puts usage
    exit -1
end

defs = DirTools.loadDefs().sort_by {|name, dir| name}

if defs.length > 0
    puts ""
end

defs.each {|x|
    puts "#{x[0]}\t\t#{x[1]}"
}

if defs.length > 0
    puts ""
end

exit 0

